import { supabase } from "@/lib/supabase";

/* =========================
   GET ALL ORDERS
========================= */
export const getOrders = async ({ status } = {}) => {
  let query = supabase
    .from("orders")
    .select(
      `
      *,
      order_items (
        id,
        quantity,
        unit_price,
        total_price,
        menu_items ( name )
      )
    `,
    )
    .order("created_at", { ascending: false });

  if (status && status !== "All") {
    query = query.eq("status", status.toLowerCase());
  }

  const { data, error } = await query;
  if (error) throw error;

  return data;
};

/* =========================
   UPDATE ORDER STATUS
========================= */
export const updateOrderStatus = async (orderId, status) => {
  const { error } = await supabase
    .from("orders")
    .update({ status: status.toLowerCase() })
    .eq("id", orderId);

  if (error) throw error;
};

/* =========================
   GET SINGLE ORDER
========================= */
export const getOrderById = async (orderId) => {
  const { data, error } = await supabase
    .from("orders")
    .select(
      `
      *,
      order_items (
        quantity,
        unit_price,
        total_price,
        menu_items ( name )
      )
    `,
    )
    .eq("id", orderId)
    .single();

  if (error) throw error;
  return data;
};

/* =========================
   CREATE ORDER
========================= */
export const createOrder = async ({ order, items }) => {
  if (!items || items.length === 0) {
    throw new Error("Order must contain at least one item");
  }

  // 1️⃣ Create order (order_number is generated by DB default)
  const { data: newOrder, error: orderError } = await supabase
    .from("orders")
    .insert({
      ...order,
      status: order.status ?? "pending",
      payment_status: order.payment_status ?? "unpaid",
    })
    .select("id, order_number, total_amount, status, created_at")
    .single();

  if (orderError) throw orderError;

  // 2️⃣ Prepare order items
  const orderItems = items.map((item) => ({
    order_id: newOrder.id,
    menu_item_id: item.menu_item_id,
    quantity: item.quantity,
    unit_price: item.unit_price,
    total_price: item.quantity * item.unit_price,
  }));

  // 3️⃣ Insert order items
  const { error: itemsError } = await supabase
    .from("order_items")
    .insert(orderItems);

  // 4️⃣ Rollback order if items fail (manual rollback)
  if (itemsError) {
    await supabase.from("orders").delete().eq("id", newOrder.id);

    throw itemsError;
  }

  return newOrder;
};
